In [6]:
import numpy as np
from pyscf import gto, scf, mp, cc

lno_num = 4
lno_list = [3e-4,1e-4,3e-5,1e-5]
lno_thresh = lno_list[lno_num-1]

a = 2 # bond length in a cluster
d = 100 # distance between each cluster
unit = 'B' # unit of length
na = 2 # size of a cluster (monomer)
nc = 2 # set as integer multiple of monomers
spin = 2 # spin per monomer
frozen = 0 # frozen orbital per monomer
elmt = 'O'
basis = 'sto6g'
atoms = ""
for n in range(nc*na):
    shift = ((n - n % na) // na) * (d-a)
    atoms += f"{elmt} {n*a+shift:.5f} 0.00000 0.00000 \n"

mol = gto.M(atom=atoms,
            basis=basis,
            verbose=4,
            unit=unit,
            symmetry=0,
            charge=0,
            spin=spin*nc,
            max_memory=4000,
            )

mf = scf.ROHF(mol).density_fit()
mf.kernel()

stable = False
while not stable:
    print(f'mean-field stability test')
    if not stable:
        mo_i, _, stable,_ = mf.stability(return_status=True)
        dm = mf.make_rdm1(mo_i,mf.mo_occ)
        mf.kernel(dm0=dm)
    elif stable:
        print(f'UHF Energy: {mf.e_tot}, stability {stable}')
        break

mymp = mp.MP2(mf).set_frozen()
mymp.kernel()

mycc = cc.CCSD(mf).set_frozen()
mycc.kernel()

print(f"HF   : {mf.e_tot}")
print(f"MP2  : {mymp.e_tot}")
print(f"CCSD : {mycc.e_tot}")

System: uname_result(system='Linux', node='sharmagroup-rn', release='7.0.0-28-generic', version='#28~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jul  1 15:50:57 UTC 2', machine='x86_64')  Threads 16
Python 3.12.13 | packaged by Anaconda, Inc. | (main, Mar 19 2026, 20:20:58) [GCC 14.3.0]
numpy 2.4.4  scipy 1.17.1  h5py 3.16.0
Date: Sun Aug  9 21:37:24 2026
PySCF version 2.12.1
PySCF path  /home/sharmagroup/sharmagroup/pyscf
GIT ORIG_HEAD 3d1768f5e33b144b606c3d2c81c12ee54d794501
GIT HEAD (branch master) f0861da51f017364d8bbaa20b742a94f3733305f

[ENV] OLD_PYSCF_EXT_PATH /home/sharmagroup/sharmagroup/pyscf-forge:
[ENV] PYSCF_EXT_PATH /home/sharmagroup/sharmagroup/pyscf-forge:/home/sharmagroup/sharmagroup/pyscf-forge:
[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 4
[INPUT] num. electrons = 32
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 4
[INPUT] symmetry 0 subgroup None
[INPUT] Mole.unit = B
[INPUT] Symbol           X                Y                Z      unit

In [3]:
print(f"HF per M   : {mf.e_tot/nc}")
print(f"MP2 per M  : {mymp.e_tot/nc}")
print(f"CCSD per M : {mycc.e_tot/nc}")

HF per M   : -148.96223484810378
MP2 per M  : -149.02625889818395
CCSD per M : -149.0398003392296


In [16]:
r2umf = mf.to_uhf()
r2umf.mo_occ

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0.]])

In [7]:
import jax
jax.config.update("jax_enable_x64", True)
from jax import random
from jax import numpy as jnp
import opt_einsum as oe

In [17]:
from afqmc.lno_afqmc import lno_afqmc, tools, prep
from pyscf.data import elements
import time, gc
lo_coeff, frag_lolist, atm_center = tools.iao_localization(r2umf)

In [15]:
options = {
           'eql_time': 10,
           'n_prop_steps': 50,
           'n_blocks': 50,
           'n_walkers': 300,
           'mix_precision': False,
           'seed': 17,
           'walker_type': 'rhf',
           'trial': 'pt2ccsd',
           }

In [ ]:
lo_coeff = lo_coeff
frag_lolist = frag_lolist
nfrozen = elements.chemcore(mol)
thresh = lno_thresh
qmc_options = options
chol_cut = 1e-5
target_sto_error = 2e-4
run_frag_list = [0]
atom_group = atm_center
    
print("\n ******* LNO-CALCULATION ******* \n")

tools.check_span(r2umf, lo_coeff, nfrozen, thresh=1e-10)

spin_type = prep.kind(lo_coeff)

if frag_lolist is None:
    if spin_type == "unrestricted":
        raise ValueError("frag_lolist must be provided for unrestricted LNO-AFQMC.")
    print("Fragment list not found. Asign every LO to a fragment.")
    frag_lolist = [[i] for i in range(lo_coeff.shape[1])]


mlno = lno_afqmc.get_lnoccsd(r2umf, lo_coeff, frag_lolist, nfrozen, thresh, spin_type)
lno_thresh = mlno.lno_thresh
lno_type = ['1h','1h']
eris = mlno.ao2mo()

nfrag_tot = len(frag_lolist)
if run_frag_list is None:
    run_frag_list = range(nfrag_tot)

frag_lolist = [frag_lolist[i] for i in run_frag_list]
nfrag_run = len(frag_lolist)

lno_pct_occ = [None, None]
lno_norb = [[None,None]] * nfrag_tot

seeds = random.randint(random.PRNGKey(qmc_options["seed"]),
                        shape=(nfrag_tot,), 
                        minval=0, 
                        maxval=100*nfrag_tot
                        )

qmc_options["max_error"] = target_sto_error / np.sqrt(nfrag_tot)
trial_base = qmc_options.get("trial", "")

las_center = [None]*nfrag_run
las_size = [None]*nfrag_run
lno_emp2 = np.zeros(nfrag_run, dtype='float64')
lno_ecc  = np.zeros(nfrag_run, dtype='float64')
lno_eqmc = np.zeros(nfrag_run, dtype='float64')
lno_eqmc_err  = np.zeros(nfrag_run, dtype='float64')
ccsd_time = np.zeros(nfrag_run, dtype='float64')
qmc_time = np.zeros(nfrag_run, dtype='float64')

mol = r2umf.mol

# Loop over fragment
for ifrag, frag_idx in enumerate(run_frag_list):
    
    loidx = frag_lolist[ifrag]

    print("\n")
    width = 80
    msg = f" {spin_type} LNO-FRAGMENT {frag_idx+1}/({nfrag_run},{nfrag_tot}) "
    print(msg.center(width, '='))
    if atom_group is not None:
        loc_ctr = f"{atom_group[frag_idx]}"
        print(f"Center Atom {loc_ctr}")
    else:
        loc_ctr = None

    orbloc, lno_param = lno_afqmc.get_lnoparam(lo_coeff, lno_thresh, lno_pct_occ, lno_norb, loidx, ifrag, spin_type)
    lno_coeff, lno_frozen, uocc_loc, _ = mlno.make_las(eris, orbloc, lno_type, lno_param)

    maskact, lno_active, nactocc, nactvir, lno_tot = \
        lno_afqmc.get_las(mlno, orbloc, uocc_loc, lno_frozen, spin_type, loc_ctr)
            
    
    time0 = time.perf_counter()
    eorb_mp2 = lno_afqmc.lnomp2_kernel(mlno, lno_coeff, lno_frozen, uocc_loc, maskact, verbose=4)
    eorb_cc, t1, t2 = \
        lno_afqmc.lnoccsd_kernel(mlno, lno_coeff, lno_frozen, uocc_loc, maskact, verbose=4)
    lnocc_time = time.perf_counter() - time0

    print(f'LNO-MP2 Orbital Energy:  {eorb_mp2:.8f}')
    print(f'LNO-CCSD Orbital Energy: {eorb_cc:.8f}')
    print(f"LNO-CCSD time:           {lnocc_time:.2f} s")

    outfile = f'fragment.out{frag_idx+1}'

    # time0 = time.perf_counter()
    # eorb_afqmc, eorb_afqmc_err \
    #     = lno_afqmc.lnoafqmc_kernel(
    #         mlno, lno_coeff, uocc_loc, lno_frozen, t1, t2, 
    #         chol_cut, frag_idx, seeds, qmc_options)
    # lnoqmc_time = time.perf_counter() - time0


 ******* LNO-CALCULATION ******* 

LO occ span the occupied MO occ space - True.
MO occ span the occupied LO occ space - False.


====================== unrestricted LNO-FRAGMENT 1/(1,1) =======================
Center Atom O
LAS occupied orbitals:  [7, 5]
LAS virtual orbitals:   [1, 3]
LAS total size:         [8, 8]

WARN: CCSD detected DF being used in the HF object. MO integrals are computed based on the DF 3-index tensors.
It's recommended to use dfccsd.CCSD for the DF-CCSD calculations

Init t2, MP2 energy = -0.0640240500701715

WARN: CCSD detected DF being used in the HF object. MO integrals are computed based on the DF 3-index tensors.
It's recommended to use dfccsd.CCSD for the DF-CCSD calculations


******** <class 'pyscf.lno.ulnoccsd.MODIFIED_UCCSD'> ********
CC2 = 0
CCSD nocc = (np.int64(7), np.int64(5)), nmo = (8, 8)
frozen orbitals [array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 19]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 17, 18, 19])]
max_cycle = 50
direct = 0
co

Traceback (most recent call last):
  File "/home/sharmagroup/sharmagroup/afqmc_lab/afqmc/afqmc/lno_afqmc/script/run_lno_afqmc_pt2ccsd.py", line 19, in <module>
    ham_data, prop, trial, wave_data, sampler, options = (prep.init_afqmc())
                                                          ^^^^^^^^^^^^^^^^^
  File "/home/sharmagroup/sharmagroup/afqmc_lab/afqmc/afqmc/lno_afqmc/prep.py", line 316, in init_afqmc
    wave_data, trial = get_wavefunction(options, nocc, norb, prjlo, amp_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sharmagroup/sharmagroup/afqmc_lab/afqmc/afqmc/lno_afqmc/prep.py", line 142, in get_wavefunction
    assert isinstance(prjlo, (np.ndarray, jax.Array))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError


UnboundLocalError: cannot access local variable 'eorb_afqmc' where it is not associated with a value

In [24]:
print(nactocc, nactvir, lno_tot)

1 1 2


In [10]:
from afqmc.lno_afqmc import prep
options = {
           'eql_time': 10,
           'n_prop_steps': 50,
           'n_blocks': 50,
           'n_walkers': 300,
           'mix_precision': False,
           'seed': 17,
           'walker_type': 'rhf',
           'trial': 'pt2ccsd',
           }

ham_data, prop, trial, wave_data, sampler, options = prep.init_afqmc(options=options)


QMC Parameters
eql_time        -         10
n_prop_steps    -         50
n_blocks        -         50
n_walkers       -        300
mix_precision   -      False
seed            -         17
walker_type     -        rhf
trial           -    pt2ccsd
dt              -      0.005
n_exp_terms     -          6
n_batch         -          1
max_error       -        0.0
nchol_chunk     -        100
max_memory      -       2000
free_projection -      False

QMC System
Number of electrons:        2
Number of orbitals:         2
Number of Cholesky Vectors: 3
Mean-Field Energy:          -10.58154201
Maximum memory per walker:            6.67 MB
Maximum number of Cholesky per chunk: 109226
Number of Cholesky chunks:            1
Number of Cholesky per chunk:         3
Number of padding Cholesky:           0


In [11]:
wave_data["rdm1"] = trial.get_rdm1(wave_data)    
ham_data = trial._build_measurement_intermediates(ham_data, wave_data)
ham_data = prop._build_propagation_intermediates(ham_data, trial, wave_data)
prop_data = prep.init_hf_prop_data(trial, wave_data, ham_data, options)


Initalize QMC walkers by HF


In [12]:
walker = prop_data["walkers"][0]

In [13]:
e_init = trial._calc_energy_restricted(walker, ham_data, wave_data)
print(e_init)

(-9.101575711129506+0j)


In [48]:
lno_frozen

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [49]:
from afqmc.lno_afqmc import integral
h0, h1, chol, nelec, norb \
    = integral.get_lno_integral(mf, lno_coeff, lno_frozen=lno_frozen, chol_cut=1e-5)
print(nelec, norb)

Size of the correlation space: 
Number of electrons: 2
Number of basis functions: 2
Build effective h0 and h1 time: 0.021796 s
Composing CDERIs from DF
Build CDERI in cLAS time: 0.006852 s
Raw CDERI in LAS shape: (180, 3)
Compress CDERI into LAS by SVD with cutoff: 1e-05
Compress CDERI time: 0.033560 s
Finished calculating Integrals
LAS Cholesky shape: (180, 3)
2 2


In [50]:
ncas, ncore, nelec, actfrag = integral.get_las_idx(mf, lno_frozen)
print(ncas, ncore, nelec, actfrag)

2 9 2 [ 9 10]


In [ ]:
from afqmc import slater_tools
bra = jnp.eye(norb)[:,:nelec//2]
ket = jnp.eye(norb)[:,:nelec//2]
slater_tools.r_energy(bra, ket, h0, h1, chol)

Array(-9.10157571+0.j, dtype=complex128)

In [54]:
jnp.eye(norb)[:,:nelec//2]

Array([[1.],
       [0.]], dtype=float64)